/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.9 public/models/waterPlane.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/waterPlane.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={5}>
        <mesh geometry={nodes.Circle_1.geometry} material={materials.layer1} />
        <mesh geometry={nodes.Circle_2.geometry} material={materials.layer2} />
        <mesh geometry={nodes.Circle_3.geometry} material={materials.layer3} />
      </group>
    </group>
  )
}

useGLTF.preload('/waterPlane.gltf')
