/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.9 public/models/kolomuya.gltf 
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useSpring, animated } from '@react-spring/three';

export function Eggscene(props) {
  const { nodes, materials } = useGLTF('./models/kolomuya.gltf');

  const STEP_DURATION = 2000;

  const { eggRotation } = useSpring({
    from: {
      eggRotation: 0,
    },
    to: [
      {
        eggRotation: -Math.PI / 2,
        delay: STEP_DURATION,
      },
      {
        eggRotation: -Math.PI,
        delay: STEP_DURATION,
      },
      {
        eggRotation: -1.5 * Math.PI,
        delay: STEP_DURATION,
      },
      {
        eggRotation: -2 * Math.PI,
        delay: STEP_DURATION,
      },
    ],
    config: {
      mass: 1,
      tension: 200,
      friction: 50,
    },
    loop: true,
    immediate: true,
  });

  return (
    <group {...props} dispose={null}>
      {/* Buildings */}
      <group position={[0.075, -0.621, 0.002]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <group position={[120.174, 143.088, -27.144]} rotation={[-Math.PI, 0, 2.967]} scale={-1}>
          <group position={[-19.532, 1.336, -13.258]} rotation={[Math.PI, 0, 2.793]} scale={-1}>
            <mesh geometry={nodes.Mesh016.geometry} material={materials.white} />
            <mesh geometry={nodes.Mesh016_1.geometry} material={materials.roof} />
          </group>
          <mesh
            geometry={nodes.Cylinder_1.geometry}
            material={nodes.Cylinder_1.material}
            position={[84.082, 0, 5.396]}
            rotation={[Math.PI / 2, Math.PI / 9, -Math.PI]}
            scale={-1}
          />
        </group>
        <group position={[120.174, -143.088, -27.144]} rotation={[0, 0, -0.175]}>
          <group position={[-19.532, 1.336, -13.258]}>
            <mesh geometry={nodes.Mesh018.geometry} material={materials.white} />
            <mesh geometry={nodes.Mesh018_1.geometry} material={materials.roof} />
          </group>
          <mesh
            geometry={nodes.Cylinder.geometry}
            material={nodes.Cylinder.material}
            position={[84.082, 0, 5.396]}
            rotation={[Math.PI / 2, 0, 0]}
          />
        </group>
      </group>
      {/* Buildings #2 */}
      <group position={[0.118, -0.192, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <group position={[111.761, -58.294, 0.362]}>
          <mesh geometry={nodes.Mesh021.geometry} material={materials.white} />
          <mesh geometry={nodes.Mesh021_1.geometry} material={materials.roof} />
        </group>
        <group position={[111.761, 58.294, 0.362]}>
          <mesh geometry={nodes.Mesh020.geometry} material={materials.white} />
          <mesh geometry={nodes.Mesh020_1.geometry} material={materials.roof} />
        </group>
      </group>
      {/* Buildings #3 */}
      <group position={[0.075, -0.676, 0.002]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <group position={[-23.664, -123.859, -11.362]}>
          <mesh geometry={nodes.Mesh030.geometry} material={materials.white} />
          <mesh geometry={nodes.Mesh030_1.geometry} material={materials.roof} />
          <mesh geometry={nodes.Mesh030_2.geometry} material={materials.glass} />
          <mesh geometry={nodes.Mesh030_3.geometry} material={materials.sidewalk} />
        </group>
        <group position={[-23.511, 123.662, -11.862]}>
          <mesh geometry={nodes.Mesh029.geometry} material={materials.white} />
          <mesh geometry={nodes.Mesh029_1.geometry} material={materials.glass} />
          <mesh geometry={nodes.Mesh029_2.geometry} material={materials.roof} />
          <mesh geometry={nodes.Mesh029_3.geometry} material={materials.sidewalk} />
        </group>
      </group>
      {/* Egg podimus */}
      <group position={[-3.204, -0.631, -0.719]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh
          geometry={nodes.Cube_1001.geometry}
          material={materials.white}
          position={[-0.015, 5.184, 10.068]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={-1}
        />
        <mesh
          geometry={nodes.Cube_1002.geometry}
          material={materials.white}
          position={[-100.015, 5.184, 10.068]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={-1}
        />
        <mesh
          geometry={nodes.Cube_1003.geometry}
          material={materials.white}
          position={[-200.015, 5.184, 10.068]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={-1}
        />
        <mesh
          geometry={nodes.Cube_1004.geometry}
          material={materials.white}
          position={[-200.015, 139.24, 10.068]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={-1}
        />
        <mesh
          geometry={nodes.Cube_1005.geometry}
          material={materials.white}
          position={[-100.015, 139.24, 10.068]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={-1}
        />
        <mesh
          geometry={nodes.Cube_1006.geometry}
          material={materials.white}
          position={[-0.015, 139.24, 10.068]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={-1}
        />
      </group>
      {/* Egg podimus */}
      <group position={[-3.204, -0.631, -0.719]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh
          geometry={nodes.Cube_2.geometry}
          material={materials.white}
          position={[-0.154, 5.314, 13.871]}
        />
        <mesh
          geometry={nodes.Cube_2001.geometry}
          material={materials.white}
          position={[-100.154, 5.314, 13.871]}
        />
        <mesh
          geometry={nodes.Cube_2002.geometry}
          material={materials.white}
          position={[-200.154, 5.314, 13.871]}
        />
        <mesh
          geometry={nodes.Cube_2003.geometry}
          material={materials.white}
          position={[-200.154, 139.37, 13.871]}
        />
        <mesh
          geometry={nodes.Cube_2004.geometry}
          material={materials.white}
          position={[-100.154, 139.37, 13.871]}
        />
        <mesh
          geometry={nodes.Cube_2005.geometry}
          material={materials.white}
          position={[-0.154, 139.37, 13.871]}
        />
      </group>
      {/* Ground  */}
      <group
        position={[-1.621, -1.065, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.01, 0.01, 0.007]}>
        <mesh geometry={nodes.Mesh.geometry} material={materials.standard_surface_1} />
        <mesh geometry={nodes.Mesh_1.geometry} material={materials.standard_surface_6} />
        <mesh geometry={nodes.Mesh_2.geometry} material={materials.standard_surface_7} />
      </group>
      <mesh
        geometry={nodes.Plane_1.geometry}
        material={materials.sidewalk}
        position={[-1.641, -0.967, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      {/* Trees  */}
      <group>
        <mesh
          geometry={nodes['Arnold_Scatter|instance_10'].geometry}
          material={materials['Material.003']}
          position={[-2.021, -0.093, 1.794]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_100'].geometry}
          material={materials['Material.001']}
          position={[-4.062, -0.634, -4.105]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_102'].geometry}
          material={materials['Material.003']}
          position={[-4.392, -0.199, 3.212]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_104'].geometry}
          material={materials['Material.001']}
          position={[-4.392, -0.612, 3.212]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_106'].geometry}
          material={materials['Material.004']}
          position={[2.737, -0.076, -3.773]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_108'].geometry}
          material={materials['Material.001']}
          position={[2.739, -0.623, -3.773]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_110'].geometry}
          material={materials['Material.003']}
          position={[2.193, -0.221, -0.759]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_112'].geometry}
          material={materials['Material.001']}
          position={[2.192, -0.633, -0.76]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_114'].geometry}
          material={materials['Material.004']}
          position={[2.128, -0.199, -2.354]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_116'].geometry}
          material={materials['Material.001']}
          position={[2.128, -0.612, -2.354]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_118'].geometry}
          material={materials['Material.003']}
          position={[0.749, -0.099, 3.108]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_12'].geometry}
          material={materials['Material.001']}
          position={[-2.019, -0.64, 1.794]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_120'].geometry}
          material={materials['Material.001']}
          position={[0.75, -0.646, 3.11]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_122'].geometry}
          material={materials['Material.004']}
          position={[1.26, -0.226, -3.429]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_124'].geometry}
          material={materials['Material.001']}
          position={[1.26, -0.638, -3.428]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_126'].geometry}
          material={materials['Material.004']}
          position={[-5.507, -0.192, 2.368]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_128'].geometry}
          material={materials['Material.001']}
          position={[-5.507, -0.606, 2.368]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_130'].geometry}
          material={materials['Material.003']}
          position={[-0.664, -0.068, 4.042]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_132'].geometry}
          material={materials['Material.001']}
          position={[-0.663, -0.615, 4.044]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_134'].geometry}
          material={materials['Material.004']}
          position={[-3.246, -0.233, -4.217]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_136'].geometry}
          material={materials['Material.001']}
          position={[-3.247, -0.645, -4.218]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_138'].geometry}
          material={materials['Material.003']}
          position={[0.794, -0.211, -4.257]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_14'].geometry}
          material={materials['Material.003']}
          position={[-1.319, -0.229, 2.683]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_140'].geometry}
          material={materials['Material.001']}
          position={[0.794, -0.624, -4.257]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_146'].geometry}
          material={materials['Material.003']}
          position={[-0.189, -0.207, -3.469]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_148'].geometry}
          material={materials['Material.001']}
          position={[-0.19, -0.619, -3.47]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_150'].geometry}
          material={materials['Material.004']}
          position={[-4.853, -0.192, -3.616]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_152'].geometry}
          material={materials['Material.001']}
          position={[-4.852, -0.606, -3.616]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_154'].geometry}
          material={materials['Material.003']}
          position={[-1.912, -0.072, 4.204]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_156'].geometry}
          material={materials['Material.001']}
          position={[-1.91, -0.619, 4.204]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_158'].geometry}
          material={materials['Material.004']}
          position={[-2.261, -0.199, -2.758]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_16'].geometry}
          material={materials['Material.001']}
          position={[-1.32, -0.641, 2.684]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_160'].geometry}
          material={materials['Material.001']}
          position={[-2.262, -0.611, -2.759]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_162'].geometry}
          material={materials['Material.004']}
          position={[2.344, -0.2, 0.638]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_164'].geometry}
          material={materials['Material.001']}
          position={[2.344, -0.614, 0.638]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_170'].geometry}
          material={materials['Material.003']}
          position={[-2.248, -0.206, 2.994]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_172'].geometry}
          material={materials['Material.001']}
          position={[-2.25, -0.618, 2.995]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_174'].geometry}
          material={materials['Material.003']}
          position={[-1.519, -0.221, -2.393]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_176'].geometry}
          material={materials['Material.001']}
          position={[-1.519, -0.634, -2.393]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_178'].geometry}
          material={materials['Material.004']}
          position={[2.684, -0.068, 4.068]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_18'].geometry}
          material={materials['Material.003']}
          position={[-3.937, -0.197, 2.332]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_180'].geometry}
          material={materials['Material.001']}
          position={[2.686, -0.614, 4.068]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_182'].geometry}
          material={materials['Material.003']}
          position={[-5.839, -0.204, -3.976]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_184'].geometry}
          material={materials['Material.001']}
          position={[-5.84, -0.617, -3.975]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_186'].geometry}
          material={materials['Material.004']}
          position={[1.261, -0.196, -2.261]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_188'].geometry}
          material={materials['Material.001']}
          position={[1.261, -0.61, -2.261]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_190'].geometry}
          material={materials['Material.004']}
          position={[1.152, -0.085, 2.197]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_192'].geometry}
          material={materials['Material.001']}
          position={[1.154, -0.632, 2.198]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_194'].geometry}
          material={materials['Material.004']}
          position={[0.525, -0.204, 4.089]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_196'].geometry}
          material={materials['Material.001']}
          position={[0.524, -0.616, 4.091]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_198'].geometry}
          material={materials['Material.003']}
          position={[-5.639, -0.222, 3.269]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_20'].geometry}
          material={materials['Material.001']}
          position={[-3.936, -0.61, 2.332]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_200'].geometry}
          material={materials['Material.001']}
          position={[-5.639, -0.636, 3.269]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_202'].geometry}
          material={materials['Material.004']}
          position={[-4.316, -0.088, -2.397]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_204'].geometry}
          material={materials['Material.001']}
          position={[-4.314, -0.635, -2.396]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_206'].geometry}
          material={materials['Material.004']}
          position={[-4.857, -0.195, 3.896]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_208'].geometry}
          material={materials['Material.001']}
          position={[-4.859, -0.607, 3.897]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_210'].geometry}
          material={nodes['Arnold_Scatter|instance_210'].material}
          position={[1.215, -0.214, 0.339]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_212'].geometry}
          material={nodes['Arnold_Scatter|instance_212'].material}
          position={[1.215, -0.627, 0.339]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_214'].geometry}
          material={materials['Material.004']}
          position={[1.742, -0.062, 2.768]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_216'].geometry}
          material={materials['Material.001']}
          position={[1.744, -0.609, 2.769]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_218'].geometry}
          material={materials['Material.004']}
          position={[-5.654, -0.202, 4.286]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_220'].geometry}
          material={materials['Material.001']}
          position={[-5.655, -0.614, 4.285]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_222'].geometry}
          material={materials['Material.004']}
          position={[2.451, -0.204, 3.19]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_224'].geometry}
          material={materials['Material.001']}
          position={[2.451, -0.617, 3.19]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_226'].geometry}
          material={materials['Material.003']}
          position={[-1.544, -0.067, -4.151]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_228'].geometry}
          material={materials['Material.001']}
          position={[-1.543, -0.614, -4.15]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_26'].geometry}
          material={materials['Material.004']}
          position={[-0.319, -0.239, 3.299]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_28'].geometry}
          material={materials['Material.001']}
          position={[-0.321, -0.651, 3.298]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_30'].geometry}
          material={materials['Material.003']}
          position={[-0.723, -0.199, -2.712]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_32'].geometry}
          material={materials['Material.001']}
          position={[-0.724, -0.613, -2.712]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_34'].geometry}
          material={materials['Material.004']}
          position={[-3.061, -0.095, 2.546]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_36'].geometry}
          material={materials['Material.001']}
          position={[-3.06, -0.642, 2.548]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_38'].geometry}
          material={materials['Material.003']}
          position={[2.694, -0.213, 2.18]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_40'].geometry}
          material={materials['Material.001']}
          position={[2.693, -0.625, 2.18]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_42'].geometry}
          material={materials['Material.004']}
          position={[-2.47, -0.193, -3.719]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_44'].geometry}
          material={materials['Material.001']}
          position={[-2.47, -0.606, -3.719]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_46'].geometry}
          material={materials['Material.003']}
          position={[2.156, -0.079, -3.187]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_48'].geometry}
          material={materials['Material.001']}
          position={[2.158, -0.626, -3.187]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_50'].geometry}
          material={materials['Material.004']}
          position={[-5.771, -0.229, -2.831]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_52'].geometry}
          material={materials['Material.001']}
          position={[-5.772, -0.641, -2.832]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_54'].geometry}
          material={materials['Material.003']}
          position={[1.768, -0.205, 3.644]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_56'].geometry}
          material={materials['Material.001']}
          position={[1.768, -0.618, 3.644]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_58'].geometry}
          material={materials['Material.003']}
          position={[0.543, -0.09, -3.034]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_6'].geometry}
          material={materials['Material.003']}
          position={[-4.141, -0.202, -3.206]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_60'].geometry}
          material={materials['Material.001']}
          position={[0.545, -0.637, -3.035]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_62'].geometry}
          material={materials['Material.003']}
          position={[-3.201, -0.236, -3.327]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_64'].geometry}
          material={materials['Material.001']}
          position={[-3.202, -0.648, -3.327]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_66'].geometry}
          material={materials['Material.004']}
          position={[-0.628, -0.207, -4.311]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_68'].geometry}
          material={materials['Material.001']}
          position={[-0.628, -0.62, -4.311]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_70'].geometry}
          material={materials['Material.003']}
          position={[1.942, -0.104, -4.108]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_72'].geometry}
          material={materials['Material.001']}
          position={[1.942, -0.651, -4.106]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_78'].geometry}
          material={materials['Material.003']}
          position={[-4.058, -0.214, 4.243]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_8'].geometry}
          material={materials['Material.001']}
          position={[-4.141, -0.616, -3.206]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_80'].geometry}
          material={materials['Material.001']}
          position={[-4.058, -0.627, 4.243]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_82'].geometry}
          material={materials['Material.004']}
          position={[-1.416, -0.085, 3.559]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_84'].geometry}
          material={materials['Material.001']}
          position={[-1.414, -0.631, 3.559]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|instance_98'].geometry}
          material={materials['Material.003']}
          position={[-4.061, -0.222, -4.104]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|Three01Cube'].geometry}
          material={materials['Material.001']}
          position={[-3.07, -0.644, 3.999]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|Three01Polygon_Reduction|NullSphere'].geometry}
          material={materials['Material.004']}
          position={[-3.072, -0.097, 3.998]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|Three02Cube'].geometry}
          material={materials['Material.001']}
          position={[-5.124, -0.625, -2.282]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|Three02Polygon_Reduction|NullSphere'].geometry}
          material={materials['Material.003']}
          position={[-5.124, -0.212, -2.282]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|Three03Cube'].geometry}
          material={materials['Material.001']}
          position={[-1.082, -0.604, -3.443]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes['Arnold_Scatter|Three03Polygon_Reduction|NullSphere'].geometry}
          material={materials['Material.004']}
          position={[-1.081, -0.192, -3.442]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
      </group>

      {/* Main egg  */}
      <mesh
        geometry={nodes.Sphere_3.geometry}
        material={materials.standard_surface_01}
        position={[0.172, 0.083, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <animated.group rotation-y={eggRotation} position={[-3.205, -0.547, -0.664]} scale={0.163}>
        <mesh geometry={nodes.Sphere001_1.geometry} material={materials['Material.017']} />
        <mesh geometry={nodes.Sphere001_2.geometry} material={materials['Material.009']} />
      </animated.group>
      <animated.group rotation-y={eggRotation} position={[-4.205, -0.547, -0.664]} scale={0.163}>
        <mesh geometry={nodes.Sphere002_1.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Sphere002_2.geometry} material={materials['Material.012']} />
      </animated.group>
      <animated.group rotation-y={eggRotation} position={[-5.205, -0.547, -0.664]} scale={0.163}>
        <mesh geometry={nodes.Sphere003_1.geometry} material={materials['Material.017']} />
        <mesh geometry={nodes.Sphere003_2.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Sphere003_3.geometry} material={materials['Material.012']} />
      </animated.group>
      <animated.group rotation-y={eggRotation} position={[-5.205, -0.547, 0.674]} scale={0.163}>
        <mesh geometry={nodes.Sphere004_1.geometry} material={materials['Material.017']} />
        <mesh geometry={nodes.Sphere004_2.geometry} material={materials['Material.009']} />
      </animated.group>
      <animated.group rotation-y={eggRotation} position={[-4.205, -0.547, 0.674]} scale={0.163}>
        <mesh geometry={nodes.Sphere005_1.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Sphere005_2.geometry} material={materials['Material.017']} />
      </animated.group>
      <animated.group rotation-y={eggRotation} position={[-3.205, -0.547, 0.674]} scale={0.163}>
        <mesh geometry={nodes.Sphere006.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Sphere006_1.geometry} material={materials['Material.012']} />
      </animated.group>
    </group>
  );
}

useGLTF.preload('./models/kolomuya.gltf');
