/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.9 public/Maps/uamap.gltf 
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Map(props) {
  const { nodes, materials } = useGLTF('/models/uamap.gltf');
  return (
    <group {...props} dispose={null}>
      <group position={[-0.029, 0.017, -0.008]} scale={0.1}>
        <mesh
          geometry={nodes.Extrude.geometry}
          material={materials.Grass}
          position={[-16.789, 0, -3.229]}
        />
        <mesh
          geometry={nodes.Extrude_1.geometry}
          material={materials.Grass}
          position={[10.222, 0, 11.897]}
        />
        <mesh
          geometry={nodes.Extrude_10.geometry}
          material={materials.Grass}
          position={[-18.69, 0, 1.323]}
        />
        <mesh
          geometry={nodes.Extrude_11.geometry}
          material={materials.Grass}
          position={[-15.451, 0, 0.846]}
        />
        <mesh
          geometry={nodes.Extrude_12.geometry}
          material={materials.Grass}
          position={[-4.805, 0, 0.403]}
        />
        <mesh
          geometry={nodes.Extrude_13.geometry}
          material={materials.Grass}
          position={[1.77, 0, -1.164]}
        />
        <mesh
          geometry={nodes.Extrude_14.geometry}
          material={materials.Grass}
          position={[21.752, 0, -0.705]}
        />
        <mesh
          geometry={nodes.Extrude_15.geometry}
          material={materials.Grass}
          position={[-12.83, 0, -1.897]}
        />
        <mesh
          geometry={nodes.Extrude_16.geometry}
          material={materials.Grass}
          position={[8.234, 0, -2.57]}
        />
        <mesh
          geometry={nodes.Extrude_17.geometry}
          material={materials.Grass}
          position={[15.276, 0, -2.567]}
        />
        <mesh
          geometry={nodes.Extrude_18.geometry}
          material={materials.Grass}
          position={[-9.136, 0, -2.181]}
        />
        <mesh
          geometry={nodes.Extrude_19.geometry}
          material={materials.Grass}
          position={[0.506, 0, -5.274]}
        />
        <mesh
          geometry={nodes.Extrude_2.geometry}
          material={materials.Grass}
          position={[-3.324, 0, 12.558]}
        />
        <mesh
          geometry={nodes.Extrude_20.geometry}
          material={materials.Grass}
          position={[-5.218, 0, -6.204]}
        />
        <mesh
          geometry={nodes.Extrude_21.geometry}
          material={materials.Grass}
          position={[-10.524, 0, -8.252]}
        />
        <mesh
          geometry={nodes.Extrude_22.geometry}
          material={materials.Grass}
          position={[-14.05, 0, -8.866]}
        />
        <mesh
          geometry={nodes.Extrude_23.geometry}
          material={materials.Grass}
          position={[3.431, 0, -9.168]}
        />
        <mesh
          geometry={nodes.Extrude_24.geometry}
          material={materials.Grass}
          position={[9.304, 0, -8.791]}
        />
        <mesh
          geometry={nodes.Extrude_25.geometry}
          material={materials.Border}
          position={[1.473, 0, 2.534]}
        />
        <mesh
          geometry={nodes.Extrude_3.geometry}
          material={materials.Grass}
          position={[-1.054, 0, 7.339]}
        />
        <mesh
          geometry={nodes.Extrude_4.geometry}
          material={materials.Grass}
          position={[13.963, 0, 6.618]}
        />
        <mesh
          geometry={nodes.Extrude_5.geometry}
          material={materials.Grass}
          position={[-11.333, 0, 2.654]}
        />
        <mesh
          geometry={nodes.Extrude_6.geometry}
          material={materials.Grass}
          position={[3.47, 0, 2.362]}
        />
        <mesh
          geometry={nodes.Extrude_7.geometry}
          material={materials.Grass}
          position={[2.983, 0, 6.415]}
        />
        <mesh
          geometry={nodes.Extrude_8.geometry}
          material={materials.Grass}
          position={[11.675, 0, 2.679]}
        />
        <mesh
          geometry={nodes.Extrude_9.geometry}
          material={materials.Grass}
          position={[19.147, 0, 3.237]}
        />
      </group>
    </group>
  );
}

useGLTF.preload('./models/uamap.gltf');
