/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/museum.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Museum(props) {
  const { nodes, materials } = useGLTF('/models/museum.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[871.933, 22.631, -47.133]}>
        <group position={[9.952, -94.087, -219.262]}>
          <group position={[0, 231.169, -0.332]} rotation={[0, 0, -Math.PI]}>
            <mesh geometry={nodes.Cube7.geometry} material={materials.Mat} position={[0, -7.602, 0]} />
          </group>
          <group position={[0, -104.825, -0.332]}>
            <mesh geometry={nodes.Cube7_1.geometry} material={materials.Mat} position={[0, -7.602, 0]} />
          </group>
          <mesh geometry={nodes.Cylinder.geometry} material={materials.Mat} position={[0, -5.816, 0.751]} />
        </group>
        <group position={[-21.833, -0.458, 38.337]}>
          <group position={[-223.233, -93.629, 0.836]}>
            <group position={[-0.482, 0, -6.011]}>
              <group position={[0, 231.169, -0.332]} rotation={[0, 0, -Math.PI]}>
                <mesh geometry={nodes.Cube7_3.geometry} material={materials.Mat} position={[0, -7.602, 0]} />
              </group>
              <group position={[0, -104.825, -0.332]}>
                <mesh geometry={nodes.Cube7_4.geometry} material={materials.Mat} position={[0, -7.602, 0]} />
              </group>
              <mesh geometry={nodes.Cylinder_1.geometry} material={materials.Mat} position={[0, -5.816, 0.751]} />
            </group>
            <group position={[255.019, 0, 256.615]}>
              <group position={[0, 231.169, -0.332]} rotation={[0, 0, -Math.PI]}>
                <mesh geometry={nodes.Cube7_5.geometry} material={materials.Mat} position={[0, -7.602, 0]} />
              </group>
              <group position={[0, -104.825, -0.332]}>
                <mesh geometry={nodes.Cube7_6.geometry} material={materials.Mat} position={[0, -7.602, 0]} />
              </group>
              <mesh geometry={nodes.Cylinder_2.geometry} material={materials.Mat} position={[0, -5.816, 0.751]} />
            </group>
            <group position={[494.518, 0, 256.615]}>
              <group position={[0, 231.169, -0.332]} rotation={[0, 0, -Math.PI]}>
                <mesh geometry={nodes.Cube7_7.geometry} material={materials.Mat} position={[0, -7.602, 0]} />
              </group>
              <group position={[0, -104.825, -0.332]}>
                <mesh geometry={nodes.Cube7_8.geometry} material={materials.Mat} position={[0, -7.602, 0]} />
              </group>
              <mesh geometry={nodes.Cylinder_3.geometry} material={materials.Mat} position={[0, -5.816, 0.751]} />
            </group>
            <group position={[494.518, 0, -256.011]}>
              <group position={[0, 231.169, -0.332]} rotation={[0, 0, -Math.PI]}>
                <mesh geometry={nodes.Cube7_9.geometry} material={materials.Mat} position={[0, -7.602, 0]} />
              </group>
              <group position={[0, -104.825, -0.332]}>
                <mesh geometry={nodes.Cube7_10.geometry} material={materials.Mat} position={[0, -7.602, 0]} />
              </group>
              <mesh geometry={nodes.Cylinder_4.geometry} material={materials.Mat} position={[0, -5.816, 0.751]} />
            </group>
            <group position={[494.518, 0, -6.011]}>
              <group position={[0, 231.169, -0.332]} rotation={[0, 0, -Math.PI]}>
                <mesh geometry={nodes.Cube7_11.geometry} material={materials.Mat} position={[0, -7.602, 0]} />
              </group>
              <group position={[0, -104.825, -0.332]}>
                <mesh geometry={nodes.Cube7_12.geometry} material={materials.Mat} position={[0, -7.602, 0]} />
              </group>
              <mesh geometry={nodes.Cylinder_5.geometry} material={materials.Mat} position={[0, -5.816, 0.751]} />
            </group>
            <group position={[0, 0, -256.011]}>
              <group position={[0, 231.169, -0.332]} rotation={[0, 0, -Math.PI]}>
                <mesh geometry={nodes.Cube7_13.geometry} material={materials.Mat} position={[0, -7.602, 0]} />
              </group>
              <group position={[0, -104.825, -0.332]}>
                <mesh geometry={nodes.Cube7_14.geometry} material={materials.Mat} position={[0, -7.602, 0]} />
              </group>
              <mesh geometry={nodes.Cylinder_6.geometry} material={materials.Mat} position={[0, -5.816, 0.751]} />
            </group>
            <group position={[0, 0, 257.023]}>
              <group position={[0, 231.169, -0.332]} rotation={[0, 0, -Math.PI]}>
                <mesh geometry={nodes.Cube7_15.geometry} material={materials.Mat} position={[0, -7.602, 0]} />
              </group>
              <group position={[0, -104.825, -0.332]}>
                <mesh geometry={nodes.Cube7_16.geometry} material={materials.Mat} position={[0, -7.602, 0]} />
              </group>
              <mesh geometry={nodes.Cylinder_7.geometry} material={materials.Mat} position={[0, -5.816, 0.751]} />
            </group>
          </group>
          <mesh geometry={nodes.Cube7_2.geometry} material={materials.Mat} position={[24.804, 426.092, 8.796]} />
        </group>
        <mesh geometry={nodes.Cube.geometry} material={materials.Mat} position={[2.97, 200.91, 43.33]} />
        <mesh geometry={nodes.Cube_1.geometry} material={materials.Mat} position={[2.97, -289.522, 47.133]} />
      </group>
    </group>
  )
}

useGLTF.preload('/museum.gltf')
