/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.9 public/models/statue.gltf 
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { Navigate, useNavigate } from 'react-router-dom';

export function Statue(props) {
  const { nodes, materials } = useGLTF('/models/statue.gltf');
  const navigate = useNavigate();

  const handleClick = () => {
    navigate('/statue');
  };

  return (
    <group onClick={handleClick} {...props} dispose={null} scale={0.1}>
      <group position={[-0.012, 1.28, -0.182]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Oleg01.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Oleg01_1.geometry} material={materials.Glass} />
      </group>
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials.Glass}
        position={[0.05, -3.14, 0.019]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Sphere.geometry}
        material={materials.Glass}
        position={[-0.004, 4.615, -0.16]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload('models/statue.gltf');
