/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.9 ./public/models/map.gltf 
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Map(props) {
  const { nodes, materials } = useGLTF('./models/map.gltf');
  return (
    <group {...props} dispose={null}>
<<<<<<< HEAD:src/pages/locations/Map.jsx
      <group position={[-0.559, 0, -0.032]} scale={50}>
        <mesh receiveShadow castShadow geometry={nodes.Curve_1.geometry} material={materials.Material} />
=======
      <group position={[-0.559, 0, -0.032]} scale={50.404}>
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.Curve_1.geometry}
          material={materials.Material}
        />
>>>>>>> develop:src/components/Map.jsx
        <mesh castShadow geometry={nodes.Curve_2.geometry} material={materials['Material.001']} />
      </group>
    </group>
  );
}

useGLTF.preload('./models/map.gltf');
